### PR TITLE
adding zinc finger to ProteinFeatures

### PR DESCRIPTION
**Pull request by pnrobinson**
@ielis 
There are many errors related to allele_count. These are not related to this PR. Is this a known issue or should I try to fix?

### CODE REVIEW

**Comment by ielis** [comment]
I do not see any issue with `allele_count` in the context of this PR. The CI fails because of a REST API timeout, which is a common issue. 
If you see 

```
UNEXPECTED EXCEPTION: HTTPError('429 Client Error: TOO MANY REQUESTS for url: https://rest.variantvalidator.org/VariantValidator/tools/gene2transcripts/NM_181486.4')
```
then pls just re-run the CI until it passes.

**Comment by pnrobinson** [comment]
Can you please check this locally? Why I run pytest in Pycharm I get about 20 errors because of this.

**Comment by ielis** [comment]
One CI ran OK (3.11), which should mean that the issue is local to your environment. The CI run for 3.10 stopped due to timeout, leading to cancellation of 3.12.

So, thanks to 3.11 finishing, I am almost sure that the PR will pass on my side.

**Comment by ielis** [comment]
Fixes #344

**Pull request merged**
